// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#include "../../ProfilerCommon.h"
#include "../../LegacyCompat.h" // Whidbey Framework Support

HRESULT VSW517637_hr;

HRESULT VSW517637_StackAllocation(IPrfCom * pPrfCom)
{
    HRESULT hr = S_OK;

    PVOID stackMemory = _alloca(100 * 0x1000);
    memset(stackMemory, NULL, 100 * 0x1000);

    VSW517637_hr = hr;

    return VSW517637_hr;
}



HRESULT VSW517637_Verify(IPrfCom * pPrfCom)
{
    if (VSW517637_hr == E_FAIL)
    {
        DISPLAY( L"VSW517637 Test Failed.\n" );
    }
    else
    {
        DISPLAY( L"VSW517637 Test Passed.\n" );
    }

    return VSW517637_hr;

}

void VSW_517637_Initialize (IPrfCom * pPrfCom, PMODULEMETHODTABLE pModuleMethodTable)
{
    DISPLAY( L"Initialize VSW517637 extension\n" );

    pModuleMethodTable->FLAGS = COR_PRF_ALL;

    pModuleMethodTable->VERIFY = (FC_VERIFY) &VSW517637_Verify;
    pModuleMethodTable->APPDOMAINCREATIONSTARTED = (FC_APPDOMAINCREATIONSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->APPDOMAINCREATIONFINISHED = (FC_APPDOMAINCREATIONFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->APPDOMAINSHUTDOWNSTARTED = (FC_APPDOMAINSHUTDOWNSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->APPDOMAINSHUTDOWNFINISHED = (FC_APPDOMAINSHUTDOWNFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->ASSEMBLYLOADSTARTED = (FC_ASSEMBLYLOADSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->ASSEMBLYLOADFINISHED = (FC_ASSEMBLYLOADFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->ASSEMBLYUNLOADSTARTED = (FC_ASSEMBLYUNLOADSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->ASSEMBLYUNLOADFINISHED = (FC_ASSEMBLYUNLOADFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->MODULELOADSTARTED = (FC_MODULELOADSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->MODULELOADFINISHED = (FC_MODULELOADFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->MODULEUNLOADSTARTED = (FC_MODULEUNLOADSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->MODULEUNLOADFINISHED = (FC_MODULEUNLOADFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->MODULEATTACHEDTOASSEMBLY = (FC_MODULEATTACHEDTOASSEMBLY) &VSW517637_StackAllocation;
    pModuleMethodTable->CLASSLOADSTARTED = (FC_CLASSLOADSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->CLASSLOADFINISHED = (FC_CLASSLOADFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->CLASSUNLOADSTARTED = (FC_CLASSUNLOADSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->CLASSUNLOADFINISHED = (FC_CLASSUNLOADFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->FUNCTIONUNLOADSTARTED = (FC_FUNCTIONUNLOADSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->JITCOMPILATIONSTARTED = (FC_JITCOMPILATIONSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->JITCOMPILATIONFINISHED = (FC_JITCOMPILATIONFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->JITCACHEDFUNCTIONSEARCHSTARTED = (FC_JITCACHEDFUNCTIONSEARCHSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->JITCACHEDFUNCTIONSEARCHFINISHED = (FC_JITCACHEDFUNCTIONSEARCHFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->JITFUNCTIONPITCHED = (FC_JITFUNCTIONPITCHED) &VSW517637_StackAllocation;
    pModuleMethodTable->JITINLINING = (FC_JITINLINING) &VSW517637_StackAllocation;
    pModuleMethodTable->THREADCREATED = (FC_THREADCREATED) &VSW517637_StackAllocation;
    pModuleMethodTable->THREADDESTROYED = (FC_THREADDESTROYED) &VSW517637_StackAllocation;
    pModuleMethodTable->THREADASSIGNEDTOOSTHREAD = (FC_THREADASSIGNEDTOOSTHREAD) &VSW517637_StackAllocation;
    pModuleMethodTable->THREADNAMECHANGED = (FC_THREADNAMECHANGED) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGCLIENTINVOCATIONSTARTED = (FC_REMOTINGCLIENTINVOCATIONSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGCLIENTSENDINGMESSAGE = (FC_REMOTINGCLIENTSENDINGMESSAGE) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGCLIENTRECEIVINGREPLY = (FC_REMOTINGCLIENTRECEIVINGREPLY) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGCLIENTINVOCATIONFINISHED = (FC_REMOTINGCLIENTINVOCATIONFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGSERVERRECEIVINGMESSAGE = (FC_REMOTINGSERVERRECEIVINGMESSAGE) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGSERVERINVOCATIONSTARTED = (FC_REMOTINGSERVERINVOCATIONSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGSERVERINVOCATIONRETURNED = (FC_REMOTINGSERVERINVOCATIONRETURNED) &VSW517637_StackAllocation;
    pModuleMethodTable->REMOTINGSERVERSENDINGREPLY = (FC_REMOTINGSERVERSENDINGREPLY) &VSW517637_StackAllocation;
    pModuleMethodTable->UNMANAGEDTOMANAGEDTRANSITION = (FC_UNMANAGEDTOMANAGEDTRANSITION) &VSW517637_StackAllocation;
    pModuleMethodTable->MANAGEDTOUNMANAGEDTRANSITION = (FC_MANAGEDTOUNMANAGEDTRANSITION) &VSW517637_StackAllocation;
    pModuleMethodTable->RUNTIMESUSPENDSTARTED = (FC_RUNTIMESUSPENDSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->RUNTIMESUSPENDFINISHED = (FC_RUNTIMESUSPENDFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->RUNTIMESUSPENDABORTED = (FC_RUNTIMESUSPENDABORTED) &VSW517637_StackAllocation;
    pModuleMethodTable->RUNTIMERESUMESTARTED = (FC_RUNTIMERESUMESTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->RUNTIMERESUMEFINISHED = (FC_RUNTIMERESUMEFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->RUNTIMETHREADSUSPENDED = (FC_RUNTIMETHREADSUSPENDED) &VSW517637_StackAllocation;
    pModuleMethodTable->RUNTIMETHREADRESUMED = (FC_RUNTIMETHREADRESUMED) &VSW517637_StackAllocation;
    pModuleMethodTable->MOVEDREFERENCES = (FC_MOVEDREFERENCES) &VSW517637_StackAllocation;
    pModuleMethodTable->OBJECTALLOCATED = (FC_OBJECTALLOCATED) &VSW517637_StackAllocation;
    pModuleMethodTable->OBJECTSALLOCATEDBYCLASS = (FC_OBJECTSALLOCATEDBYCLASS) &VSW517637_StackAllocation;
    pModuleMethodTable->OBJECTREFERENCES = (FC_OBJECTREFERENCES) &VSW517637_StackAllocation;
    pModuleMethodTable->ROOTREFERENCES = (FC_ROOTREFERENCES) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONTHROWN = (FC_EXCEPTIONTHROWN) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONSEARCHFUNCTIONENTER = (FC_EXCEPTIONSEARCHFUNCTIONENTER) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONSEARCHFUNCTIONLEAVE = (FC_EXCEPTIONSEARCHFUNCTIONLEAVE) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONSEARCHFILTERENTER = (FC_EXCEPTIONSEARCHFILTERENTER) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONSEARCHFILTERLEAVE = (FC_EXCEPTIONSEARCHFILTERLEAVE) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONSEARCHCATCHERFOUND = (FC_EXCEPTIONSEARCHCATCHERFOUND) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONOSHANDLERENTER = (FC_EXCEPTIONOSHANDLERENTER) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONOSHANDLERLEAVE = (FC_EXCEPTIONOSHANDLERLEAVE) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONUNWINDFUNCTIONENTER = (FC_EXCEPTIONUNWINDFUNCTIONENTER) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONUNWINDFUNCTIONLEAVE = (FC_EXCEPTIONUNWINDFUNCTIONLEAVE) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONUNWINDFINALLYENTER = (FC_EXCEPTIONUNWINDFINALLYENTER) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONUNWINDFINALLYLEAVE = (FC_EXCEPTIONUNWINDFINALLYLEAVE) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONCATCHERENTER = (FC_EXCEPTIONCATCHERENTER) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONCATCHERLEAVE = (FC_EXCEPTIONCATCHERLEAVE) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONCLRCATCHERFOUND = (FC_EXCEPTIONCLRCATCHERFOUND) &VSW517637_StackAllocation;
    pModuleMethodTable->EXCEPTIONCLRCATCHEREXECUTE = (FC_EXCEPTIONCLRCATCHEREXECUTE) &VSW517637_StackAllocation;
    pModuleMethodTable->COMCLASSICVTABLECREATED = (FC_COMCLASSICVTABLECREATED) &VSW517637_StackAllocation;
    pModuleMethodTable->COMCLASSICVTABLEDESTROYED = (FC_COMCLASSICVTABLEDESTROYED) &VSW517637_StackAllocation;
    pModuleMethodTable->GARBAGECOLLECTIONSTARTED = (FC_GARBAGECOLLECTIONSTARTED) &VSW517637_StackAllocation;
    pModuleMethodTable->GARBAGECOLLECTIONFINISHED = (FC_GARBAGECOLLECTIONFINISHED) &VSW517637_StackAllocation;
    pModuleMethodTable->FINALIZEABLEOBJECTQUEUED = (FC_FINALIZEABLEOBJECTQUEUED) &VSW517637_StackAllocation;
    pModuleMethodTable->ROOTREFERENCES2 = (FC_ROOTREFERENCES2) &VSW517637_StackAllocation;
    pModuleMethodTable->HANDLECREATED = (FC_HANDLECREATED) &VSW517637_StackAllocation;
    pModuleMethodTable->HANDLEDESTROYED = (FC_HANDLEDESTROYED) &VSW517637_StackAllocation;
    pModuleMethodTable->SURVIVINGREFERENCES = (FC_SURVIVINGREFERENCES) &VSW517637_StackAllocation;
    pModuleMethodTable->FUNCTIONENTER2 = (FC_FUNCTIONENTER2) &VSW517637_StackAllocation;
    pModuleMethodTable->FUNCTIONTAILCALL2 = (FC_FUNCTIONTAILCALL2) &VSW517637_StackAllocation;
    pModuleMethodTable->FUNCTIONLEAVE2 = (FC_FUNCTIONLEAVE2) &VSW517637_StackAllocation;

    VSW517637_hr = E_FAIL;
    return;
}

